-- ReadWell Level 1 Baseline Assessment, Form A, as the KG 1 assessment.
--
-- KG 1 is grade -1 (and KG 2 is 0), so kindergarten sorts below Grade 1;
-- see src/lib/grades.ts. This form is assessor-led: a trained adult gives
-- it one to one on the assessor screen and taps right or wrong for each
-- item, and the app applies the guide's gate rules. Its items are
-- generated from the item bank in src/lib/readwell/level1FormA.ts, which
-- reproduces the assessor guide word for word; src/lib/readwell/
-- seedSql.test.ts fails if this copy and the item bank ever differ.
--
-- The strand skill areas are added where missing. Vocabulary is shared
-- with the Grade 1 starter content (setup.sql, seed.sql), so it isn't
-- inserted here: seed.sql adds it with a fixed id after migrations run.
-- Only added where no KG 1 assessment exists, so this never replaces one.

insert into public.skill_areas (key, name) values
  ('storyListening', 'Story listening'),
  ('printConcepts', 'Print concepts'),
  ('soundAwareness', 'Sound awareness'),
  ('letterNames', 'Letter names'),
  ('letterSounds', 'Letter sounds'),
  ('wordReading', 'Word reading'),
  ('heartWords', 'Heart words'),
  ('storyQuestions', 'Story questions'),
  ('writing', 'Writing')
on conflict (key) do nothing;

insert into public.assessments (grade_level, version, items, is_active)
select -1, 1, '[
    {"id":"L1A.LC.01","skillAreaKey":"storyListening","type":"assessor","part":1,"prompt":"What animal does Kwaku have?","accept":"A goat"},
    {"id":"L1A.LC.02","skillAreaKey":"storyListening","type":"assessor","part":1,"prompt":"What does Kwaku give the goat every morning?","accept":"Water"},
    {"id":"L1A.LC.03","skillAreaKey":"storyListening","type":"assessor","part":1,"prompt":"Where did Kwaku find the goat?","accept":"In the kitchen"},
    {"id":"L1A.LC.04","skillAreaKey":"storyListening","type":"assessor","part":1,"prompt":"Why was the goat able to run away?","accept":"The gate was open"},
    {"id":"L1A.LC.05","skillAreaKey":"storyListening","type":"assessor","part":1,"prompt":"Why do you think Kwaku tied the goat with a rope?","accept":"So it cannot run away again, or any sensible reason"},
    {"id":"L1A.VO.01","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"ram","detail":"hen, ram, dog, fish","accept":"Picture 2 (ram)"},
    {"id":"L1A.VO.02","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"web","detail":"net, rope, web, nest","accept":"Picture 3 (web)"},
    {"id":"L1A.VO.03","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"hut","detail":"hut, tent, car, tree","accept":"Picture 1 (hut)"},
    {"id":"L1A.VO.04","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"mop","detail":"broom, brush, bucket, mop","accept":"Picture 4 (mop)"},
    {"id":"L1A.VO.05","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"tin","detail":"cup, tin, bottle, basket","accept":"Picture 2 (tin)"},
    {"id":"L1A.VO.06","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"bucket","detail":"pot, bowl, basket, bucket","accept":"Picture 4 (bucket)"},
    {"id":"L1A.VO.07","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"ladder","detail":"ladder, chair, table, door","accept":"Picture 1 (ladder)"},
    {"id":"L1A.VO.08","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"bridge","detail":"road, river, bridge, gate","accept":"Picture 3 (bridge)"},
    {"id":"L1A.VO.09","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"roof","detail":"window, roof, door, wall","accept":"Picture 2 (roof)"},
    {"id":"L1A.VO.10","skillAreaKey":"vocabulary","type":"assessor","part":2,"prompt":"farmer","detail":"teacher, driver, farmer, doctor","accept":"Picture 3 (farmer)"},
    {"id":"L1A.CP.01","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Show me the front of this book.","accept":"Turns to or points to the front cover"},
    {"id":"L1A.CP.02","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Show me the back of the book.","accept":"Points to the back cover"},
    {"id":"L1A.CP.03","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Open the book so that we can read it.","accept":"Opens from the front with the book the right way up"},
    {"id":"L1A.CP.04","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"I want to read this page. Show me where I start reading.","accept":"Points to the first word of the first line, not the picture","instruction":"Now turn to page 4 yourself."},
    {"id":"L1A.CP.05","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Which way do I go from there?","accept":"Moves a finger from left to right along the line"},
    {"id":"L1A.CP.06","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Where do I go after that?","accept":"Moves down to the start of the next line"},
    {"id":"L1A.CP.07","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Show me just one letter.","accept":"Points to or covers one letter only"},
    {"id":"L1A.CP.08","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Show me just one word.","accept":"Points to or frames one whole word"},
    {"id":"L1A.CP.09","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Show me a capital letter.","accept":"Points to any capital letter"},
    {"id":"L1A.CP.10","skillAreaKey":"printConcepts","type":"assessor","part":3,"prompt":"Show me a full stop.","accept":"Points to any full stop"},
    {"id":"L1A.SA.1.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":1,"prompt":"Rung 1, item 1"},
    {"id":"L1A.SA.1.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":1,"prompt":"Rung 1, item 2"},
    {"id":"L1A.SA.1.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":1,"prompt":"Rung 1, item 3"},
    {"id":"L1A.SA.1.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":1,"prompt":"Rung 1, item 4"},
    {"id":"L1A.SA.1.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":1,"prompt":"Rung 1, item 5"},
    {"id":"L1A.SA.2.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":2,"prompt":"Rung 2, item 1"},
    {"id":"L1A.SA.2.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":2,"prompt":"Rung 2, item 2"},
    {"id":"L1A.SA.2.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":2,"prompt":"Rung 2, item 3"},
    {"id":"L1A.SA.2.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":2,"prompt":"Rung 2, item 4"},
    {"id":"L1A.SA.2.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":2,"prompt":"Rung 2, item 5"},
    {"id":"L1A.SA.3.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":3,"prompt":"Rung 3, item 1"},
    {"id":"L1A.SA.3.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":3,"prompt":"Rung 3, item 2"},
    {"id":"L1A.SA.3.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":3,"prompt":"Rung 3, item 3"},
    {"id":"L1A.SA.3.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":3,"prompt":"Rung 3, item 4"},
    {"id":"L1A.SA.3.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":3,"prompt":"Rung 3, item 5"},
    {"id":"L1A.SA.4.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":4,"prompt":"Rung 4, item 1"},
    {"id":"L1A.SA.4.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":4,"prompt":"Rung 4, item 2"},
    {"id":"L1A.SA.4.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":4,"prompt":"Rung 4, item 3"},
    {"id":"L1A.SA.4.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":4,"prompt":"Rung 4, item 4"},
    {"id":"L1A.SA.4.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":4,"prompt":"Rung 4, item 5"},
    {"id":"L1A.SA.5.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":5,"prompt":"Rung 5, item 1"},
    {"id":"L1A.SA.5.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":5,"prompt":"Rung 5, item 2"},
    {"id":"L1A.SA.5.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":5,"prompt":"Rung 5, item 3"},
    {"id":"L1A.SA.5.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":5,"prompt":"Rung 5, item 4"},
    {"id":"L1A.SA.5.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":5,"prompt":"Rung 5, item 5"},
    {"id":"L1A.SA.6.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":6,"prompt":"Rung 6, item 1"},
    {"id":"L1A.SA.6.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":6,"prompt":"Rung 6, item 2"},
    {"id":"L1A.SA.6.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":6,"prompt":"Rung 6, item 3"},
    {"id":"L1A.SA.6.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":6,"prompt":"Rung 6, item 4"},
    {"id":"L1A.SA.6.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":6,"prompt":"Rung 6, item 5"},
    {"id":"L1A.SA.7.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":7,"prompt":"Rung 7, item 1"},
    {"id":"L1A.SA.7.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":7,"prompt":"Rung 7, item 2"},
    {"id":"L1A.SA.7.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":7,"prompt":"Rung 7, item 3"},
    {"id":"L1A.SA.7.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":7,"prompt":"Rung 7, item 4"},
    {"id":"L1A.SA.7.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":7,"prompt":"Rung 7, item 5"},
    {"id":"L1A.SA.8.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":8,"prompt":"Rung 8, item 1"},
    {"id":"L1A.SA.8.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":8,"prompt":"Rung 8, item 2"},
    {"id":"L1A.SA.8.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":8,"prompt":"Rung 8, item 3"},
    {"id":"L1A.SA.8.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":8,"prompt":"Rung 8, item 4"},
    {"id":"L1A.SA.8.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":8,"prompt":"Rung 8, item 5"},
    {"id":"L1A.SA.9.1","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":9,"prompt":"Rung 9, item 1"},
    {"id":"L1A.SA.9.2","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":9,"prompt":"Rung 9, item 2"},
    {"id":"L1A.SA.9.3","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":9,"prompt":"Rung 9, item 3"},
    {"id":"L1A.SA.9.4","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":9,"prompt":"Rung 9, item 4"},
    {"id":"L1A.SA.9.5","skillAreaKey":"soundAwareness","type":"assessor","part":4,"row":9,"prompt":"Rung 9, item 5"},
    {"id":"L1A.LN.01","skillAreaKey":"letterNames","type":"assessor","part":5,"row":1,"prompt":"s"},
    {"id":"L1A.LN.02","skillAreaKey":"letterNames","type":"assessor","part":5,"row":1,"prompt":"m"},
    {"id":"L1A.LN.03","skillAreaKey":"letterNames","type":"assessor","part":5,"row":1,"prompt":"a"},
    {"id":"L1A.LN.04","skillAreaKey":"letterNames","type":"assessor","part":5,"row":1,"prompt":"t"},
    {"id":"L1A.LN.05","skillAreaKey":"letterNames","type":"assessor","part":5,"row":1,"prompt":"o"},
    {"id":"L1A.LN.06","skillAreaKey":"letterNames","type":"assessor","part":5,"row":1,"prompt":"b"},
    {"id":"L1A.LN.07","skillAreaKey":"letterNames","type":"assessor","part":5,"row":2,"prompt":"k"},
    {"id":"L1A.LN.08","skillAreaKey":"letterNames","type":"assessor","part":5,"row":2,"prompt":"e"},
    {"id":"L1A.LN.09","skillAreaKey":"letterNames","type":"assessor","part":5,"row":2,"prompt":"w"},
    {"id":"L1A.LN.10","skillAreaKey":"letterNames","type":"assessor","part":5,"row":2,"prompt":"d"},
    {"id":"L1A.LN.11","skillAreaKey":"letterNames","type":"assessor","part":5,"row":2,"prompt":"r"},
    {"id":"L1A.LN.12","skillAreaKey":"letterNames","type":"assessor","part":5,"row":2,"prompt":"i"},
    {"id":"L1A.LN.13","skillAreaKey":"letterNames","type":"assessor","part":5,"row":3,"prompt":"n"},
    {"id":"L1A.LN.14","skillAreaKey":"letterNames","type":"assessor","part":5,"row":3,"prompt":"z"},
    {"id":"L1A.LN.15","skillAreaKey":"letterNames","type":"assessor","part":5,"row":3,"prompt":"c"},
    {"id":"L1A.LN.16","skillAreaKey":"letterNames","type":"assessor","part":5,"row":3,"prompt":"f"},
    {"id":"L1A.LN.17","skillAreaKey":"letterNames","type":"assessor","part":5,"row":3,"prompt":"u"},
    {"id":"L1A.LN.18","skillAreaKey":"letterNames","type":"assessor","part":5,"row":3,"prompt":"h"},
    {"id":"L1A.LN.19","skillAreaKey":"letterNames","type":"assessor","part":5,"row":4,"prompt":"p"},
    {"id":"L1A.LN.20","skillAreaKey":"letterNames","type":"assessor","part":5,"row":4,"prompt":"x"},
    {"id":"L1A.LN.21","skillAreaKey":"letterNames","type":"assessor","part":5,"row":4,"prompt":"g"},
    {"id":"L1A.LN.22","skillAreaKey":"letterNames","type":"assessor","part":5,"row":4,"prompt":"l"},
    {"id":"L1A.LN.23","skillAreaKey":"letterNames","type":"assessor","part":5,"row":4,"prompt":"j"},
    {"id":"L1A.LN.24","skillAreaKey":"letterNames","type":"assessor","part":5,"row":4,"prompt":"y"},
    {"id":"L1A.LN.25","skillAreaKey":"letterNames","type":"assessor","part":5,"row":5,"prompt":"v"},
    {"id":"L1A.LN.26","skillAreaKey":"letterNames","type":"assessor","part":5,"row":5,"prompt":"q"},
    {"id":"L1A.LS.01","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":1,"prompt":"a","accept":"The short sound only"},
    {"id":"L1A.LS.02","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":1,"prompt":"t","accept":"/t/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.03","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":1,"prompt":"s","accept":"/s/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.04","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":1,"prompt":"m","accept":"/m/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.05","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":1,"prompt":"p","accept":"/p/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.06","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":1,"prompt":"n","accept":"/n/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.07","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":2,"prompt":"g","accept":"/g/ as in goat"},
    {"id":"L1A.LS.08","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":2,"prompt":"i","accept":"The short sound only"},
    {"id":"L1A.LS.09","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":2,"prompt":"h","accept":"/h/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.10","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":2,"prompt":"d","accept":"/d/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.11","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":2,"prompt":"u","accept":"The short sound only"},
    {"id":"L1A.LS.12","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":2,"prompt":"c","accept":"/k/"},
    {"id":"L1A.LS.13","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":3,"prompt":"f","accept":"/f/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.14","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":3,"prompt":"o","accept":"The short sound only"},
    {"id":"L1A.LS.15","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":3,"prompt":"l","accept":"/l/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.16","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":3,"prompt":"y","accept":"/y/ as in yam"},
    {"id":"L1A.LS.17","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":3,"prompt":"b","accept":"/b/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.18","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":3,"prompt":"r","accept":"/r/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.19","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":4,"prompt":"e","accept":"The short sound only"},
    {"id":"L1A.LS.20","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":4,"prompt":"k","accept":"/k/"},
    {"id":"L1A.LS.21","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":4,"prompt":"w","accept":"/w/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.22","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":4,"prompt":"j","accept":"/j/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.23","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":4,"prompt":"z","accept":"/z/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.24","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":4,"prompt":"v","accept":"/v/ (a small extra vowel is still correct)"},
    {"id":"L1A.LS.25","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":5,"prompt":"x","accept":"/ks/ as at the end of fox"},
    {"id":"L1A.LS.26","skillAreaKey":"letterSounds","type":"assessor","part":6,"row":5,"prompt":"q","accept":"/kw/"},
    {"id":"L1A.CV.01","skillAreaKey":"wordReading","type":"assessor","part":7,"row":1,"prompt":"ma"},
    {"id":"L1A.CV.02","skillAreaKey":"wordReading","type":"assessor","part":7,"row":1,"prompt":"fe"},
    {"id":"L1A.CV.03","skillAreaKey":"wordReading","type":"assessor","part":7,"row":1,"prompt":"ti"},
    {"id":"L1A.CV.04","skillAreaKey":"wordReading","type":"assessor","part":7,"row":1,"prompt":"po"},
    {"id":"L1A.CV.05","skillAreaKey":"wordReading","type":"assessor","part":7,"row":1,"prompt":"su"},
    {"id":"L1A.CV.06","skillAreaKey":"wordReading","type":"assessor","part":7,"row":2,"prompt":"da"},
    {"id":"L1A.CV.07","skillAreaKey":"wordReading","type":"assessor","part":7,"row":2,"prompt":"ne"},
    {"id":"L1A.CV.08","skillAreaKey":"wordReading","type":"assessor","part":7,"row":2,"prompt":"li"},
    {"id":"L1A.CV.09","skillAreaKey":"wordReading","type":"assessor","part":7,"row":2,"prompt":"bo"},
    {"id":"L1A.CV.10","skillAreaKey":"wordReading","type":"assessor","part":7,"row":2,"prompt":"gu"},
    {"id":"L1A.RW.01","skillAreaKey":"wordReading","type":"assessor","part":8,"row":1,"prompt":"gap"},
    {"id":"L1A.RW.02","skillAreaKey":"wordReading","type":"assessor","part":8,"row":1,"prompt":"den"},
    {"id":"L1A.RW.03","skillAreaKey":"wordReading","type":"assessor","part":8,"row":1,"prompt":"rip"},
    {"id":"L1A.RW.04","skillAreaKey":"wordReading","type":"assessor","part":8,"row":1,"prompt":"jog"},
    {"id":"L1A.RW.05","skillAreaKey":"wordReading","type":"assessor","part":8,"row":1,"prompt":"bug"},
    {"id":"L1A.RW.06","skillAreaKey":"wordReading","type":"assessor","part":8,"row":2,"prompt":"yes"},
    {"id":"L1A.RW.07","skillAreaKey":"wordReading","type":"assessor","part":8,"row":2,"prompt":"dim"},
    {"id":"L1A.RW.08","skillAreaKey":"wordReading","type":"assessor","part":8,"row":2,"prompt":"lap"},
    {"id":"L1A.RW.09","skillAreaKey":"wordReading","type":"assessor","part":8,"row":2,"prompt":"hum"},
    {"id":"L1A.RW.10","skillAreaKey":"wordReading","type":"assessor","part":8,"row":2,"prompt":"fog"},
    {"id":"L1A.RW.11","skillAreaKey":"wordReading","type":"assessor","part":8,"row":3,"prompt":"rib"},
    {"id":"L1A.RW.12","skillAreaKey":"wordReading","type":"assessor","part":8,"row":3,"prompt":"lot"},
    {"id":"L1A.RW.13","skillAreaKey":"wordReading","type":"assessor","part":8,"row":3,"prompt":"wag"},
    {"id":"L1A.RW.14","skillAreaKey":"wordReading","type":"assessor","part":8,"row":3,"prompt":"met"},
    {"id":"L1A.RW.15","skillAreaKey":"wordReading","type":"assessor","part":8,"row":3,"prompt":"bud"},
    {"id":"L1A.RW.16","skillAreaKey":"wordReading","type":"assessor","part":8,"row":4,"prompt":"pop"},
    {"id":"L1A.RW.17","skillAreaKey":"wordReading","type":"assessor","part":8,"row":4,"prompt":"tug"},
    {"id":"L1A.RW.18","skillAreaKey":"wordReading","type":"assessor","part":8,"row":4,"prompt":"bet"},
    {"id":"L1A.RW.19","skillAreaKey":"wordReading","type":"assessor","part":8,"row":4,"prompt":"hip"},
    {"id":"L1A.RW.20","skillAreaKey":"wordReading","type":"assessor","part":8,"row":4,"prompt":"bad"},
    {"id":"L1A.NW.01","skillAreaKey":"wordReading","type":"assessor","part":9,"row":1,"prompt":"vap"},
    {"id":"L1A.NW.02","skillAreaKey":"wordReading","type":"assessor","part":9,"row":1,"prompt":"teg"},
    {"id":"L1A.NW.03","skillAreaKey":"wordReading","type":"assessor","part":9,"row":1,"prompt":"nim"},
    {"id":"L1A.NW.04","skillAreaKey":"wordReading","type":"assessor","part":9,"row":1,"prompt":"dob"},
    {"id":"L1A.NW.05","skillAreaKey":"wordReading","type":"assessor","part":9,"row":1,"prompt":"fum"},
    {"id":"L1A.NW.06","skillAreaKey":"wordReading","type":"assessor","part":9,"row":2,"prompt":"zat"},
    {"id":"L1A.NW.07","skillAreaKey":"wordReading","type":"assessor","part":9,"row":2,"prompt":"pib"},
    {"id":"L1A.NW.08","skillAreaKey":"wordReading","type":"assessor","part":9,"row":2,"prompt":"vog"},
    {"id":"L1A.NW.09","skillAreaKey":"wordReading","type":"assessor","part":9,"row":2,"prompt":"lut"},
    {"id":"L1A.NW.10","skillAreaKey":"wordReading","type":"assessor","part":9,"row":2,"prompt":"fep"},
    {"id":"L1A.HW.01","skillAreaKey":"heartWords","type":"assessor","part":10,"row":1,"prompt":"the","detail":"Set 1"},
    {"id":"L1A.HW.02","skillAreaKey":"heartWords","type":"assessor","part":10,"row":1,"prompt":"of","detail":"Set 1"},
    {"id":"L1A.HW.03","skillAreaKey":"heartWords","type":"assessor","part":10,"row":1,"prompt":"she","detail":"Set 2"},
    {"id":"L1A.HW.04","skillAreaKey":"heartWords","type":"assessor","part":10,"row":1,"prompt":"have","detail":"Set 2"},
    {"id":"L1A.HW.05","skillAreaKey":"heartWords","type":"assessor","part":10,"row":1,"prompt":"are","detail":"Set 3"},
    {"id":"L1A.HW.06","skillAreaKey":"heartWords","type":"assessor","part":10,"row":2,"prompt":"go","detail":"Set 3"},
    {"id":"L1A.HW.07","skillAreaKey":"heartWords","type":"assessor","part":10,"row":2,"prompt":"with","detail":"Set 4"},
    {"id":"L1A.HW.08","skillAreaKey":"heartWords","type":"assessor","part":10,"row":2,"prompt":"he","detail":"Set 4"},
    {"id":"L1A.HW.09","skillAreaKey":"heartWords","type":"assessor","part":10,"row":2,"prompt":"was","detail":"Set 5"},
    {"id":"L1A.HW.10","skillAreaKey":"heartWords","type":"assessor","part":10,"row":2,"prompt":"you","detail":"Set 5"},
    {"id":"L1A.HW.11","skillAreaKey":"heartWords","type":"assessor","part":10,"row":3,"prompt":"said","detail":"Set 6"},
    {"id":"L1A.HW.12","skillAreaKey":"heartWords","type":"assessor","part":10,"row":3,"prompt":"there","detail":"Set 6"},
    {"id":"L1A.HW.13","skillAreaKey":"heartWords","type":"assessor","part":10,"row":3,"prompt":"look","detail":"Set 7"},
    {"id":"L1A.HW.14","skillAreaKey":"heartWords","type":"assessor","part":10,"row":3,"prompt":"like","detail":"Set 7"},
    {"id":"L1A.HW.15","skillAreaKey":"heartWords","type":"assessor","part":10,"row":3,"prompt":"down","detail":"Set 8"},
    {"id":"L1A.HW.16","skillAreaKey":"heartWords","type":"assessor","part":10,"row":4,"prompt":"for","detail":"Set 8"},
    {"id":"L1A.HW.17","skillAreaKey":"heartWords","type":"assessor","part":10,"row":4,"prompt":"saw","detail":"Set 9"},
    {"id":"L1A.HW.18","skillAreaKey":"heartWords","type":"assessor","part":10,"row":4,"prompt":"away","detail":"Set 9"},
    {"id":"L1A.HW.19","skillAreaKey":"heartWords","type":"assessor","part":10,"row":4,"prompt":"happy","detail":"Set 10"},
    {"id":"L1A.HW.20","skillAreaKey":"heartWords","type":"assessor","part":10,"row":4,"prompt":"where","detail":"Set 10"},
    {"id":"L1A.ST.READ","skillAreaKey":"storyQuestions","type":"assessor","part":11,"prompt":"Tim and the pup","scored":false},
    {"id":"L1A.STQ.01","skillAreaKey":"storyQuestions","type":"assessor","part":11,"prompt":"What does Tim have?","accept":"A bag, or a big red bag","fromLine":1},
    {"id":"L1A.STQ.02","skillAreaKey":"storyQuestions","type":"assessor","part":11,"prompt":"Where did the pup hide?","accept":"In the bag","fromLine":2},
    {"id":"L1A.STQ.03","skillAreaKey":"storyQuestions","type":"assessor","part":11,"prompt":"What did Tim say to the pup?","accept":"No","fromLine":3},
    {"id":"L1A.STQ.04","skillAreaKey":"storyQuestions","type":"assessor","part":11,"prompt":"Where did the pup sit?","accept":"On his leg, or on Tim''s leg","fromLine":5},
    {"id":"L1A.STQ.05","skillAreaKey":"storyQuestions","type":"assessor","part":11,"prompt":"Why do you think Tim is happy at the end?","accept":"He likes the pup, he has a friend, or any sensible reason from the story","fromLine":7},
    {"id":"L1A.AT.01","skillAreaKey":"readingAttitude","type":"assessor","part":12,"prompt":"How do you feel when someone reads a story to you?","scored":false,"responseChoices":[{"label":"Happy","value":3},{"label":"Just okay","value":2},{"label":"Sad","value":1}]},
    {"id":"L1A.AT.02","skillAreaKey":"readingAttitude","type":"assessor","part":12,"prompt":"How do you feel when you look at books by yourself?","scored":false,"responseChoices":[{"label":"Happy","value":3},{"label":"Just okay","value":2},{"label":"Sad","value":1}]},
    {"id":"L1A.AT.03","skillAreaKey":"readingAttitude","type":"assessor","part":12,"prompt":"How do you feel about learning to read?","scored":false,"responseChoices":[{"label":"Happy","value":3},{"label":"Just okay","value":2},{"label":"Sad","value":1}]},
    {"id":"L1A.AT.04","skillAreaKey":"readingAttitude","type":"assessor","part":12,"prompt":"Does someone at home read or tell stories with you?","scored":false,"responseChoices":[{"label":"Yes","value":"yes"},{"label":"Sometimes","value":"sometimes"},{"label":"No","value":"no"}]},
    {"id":"L1A.WT.01","skillAreaKey":"writing","type":"assessor","part":13,"row":1,"prompt":"Write your name on the first line.","maxScore":2,"accept":"2: The whole first name, readable. 1: The first letter, or at least two letters of the name. 0: Nothing, or marks that are not letters."},
    {"id":"L1A.WT.02","skillAreaKey":"writing","type":"assessor","part":13,"row":2,"prompt":"/s/","accept":"s"},
    {"id":"L1A.WT.03","skillAreaKey":"writing","type":"assessor","part":13,"row":2,"prompt":"/m/","accept":"m"},
    {"id":"L1A.WT.04","skillAreaKey":"writing","type":"assessor","part":13,"row":2,"prompt":"/t/","accept":"t"},
    {"id":"L1A.WT.05","skillAreaKey":"writing","type":"assessor","part":13,"row":2,"prompt":"/b/","accept":"b"},
    {"id":"L1A.WT.06","skillAreaKey":"writing","type":"assessor","part":13,"row":2,"prompt":"/i/","accept":"i"},
    {"id":"L1A.WT.07","skillAreaKey":"writing","type":"assessor","part":13,"row":3,"prompt":"tag","detail":"The shirt has a tag.","accept":"All three letters are correct and in the right order"},
    {"id":"L1A.WT.08","skillAreaKey":"writing","type":"assessor","part":13,"row":3,"prompt":"peg","detail":"Hang the cloth with a peg.","accept":"All three letters are correct and in the right order"},
    {"id":"L1A.WT.09","skillAreaKey":"writing","type":"assessor","part":13,"row":3,"prompt":"job","detail":"My mother has a job.","accept":"All three letters are correct and in the right order"},
    {"id":"L1A.WT.10","skillAreaKey":"writing","type":"assessor","part":13,"row":3,"prompt":"bun","detail":"I ate a bun.","accept":"All three letters are correct and in the right order"},
    {"id":"L1A.WT.11","skillAreaKey":"writing","type":"assessor","part":13,"row":4,"prompt":"The sentence starts with a capital letter"},
    {"id":"L1A.WT.12","skillAreaKey":"writing","type":"assessor","part":13,"row":4,"prompt":"There are clear spaces between the words"},
    {"id":"L1A.WT.13","skillAreaKey":"writing","type":"assessor","part":13,"row":4,"prompt":"The sentence ends with a full stop"},
    {"id":"L1A.WT.14","skillAreaKey":"writing","type":"assessor","part":13,"row":4,"prompt":"At least three of the five words are spelled correctly"}
  ]'::jsonb, true
where not exists (select 1 from public.assessments where grade_level = -1);
